# Generated by Django 6.0.6 on 2026-07-01 04:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('status', models.CharField(choices=[('PRE_RESERVADO', 'Pré-reservado'), ('CONFIRMADO', 'Confirmado'), ('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('CANCELADO', 'Cancelado')], default='PRE_RESERVADO', max_length=30, verbose_name='Status do Show')),
                ('date', models.DateField(verbose_name='Data')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('venue', models.CharField(max_length=200, verbose_name='Local')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Saída')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='Horário de Chegada')),
                ('soundcheck_time', models.TimeField(blank=True, null=True, verbose_name='Horário da Passagem de Som')),
                ('show_time', models.TimeField(blank=True, null=True, verbose_name='Horário do Show')),
                ('duration', models.CharField(blank=True, help_text='Ex: 2 horas', max_length=50, null=True, verbose_name='Duração do Show')),
                ('contractor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contratante')),
                ('contractor_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Contratante')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Cachê')),
                ('payment_status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Pago Parcialmente'), ('PAGO', 'Pago Totalmente')], default='PENDENTE', max_length=20, verbose_name='Status do Pagamento')),
                ('transport', models.TextField(blank=True, null=True, verbose_name='Transporte')),
                ('accommodation', models.TextField(blank=True, null=True, verbose_name='Hospedagem')),
                ('dressing_room', models.TextField(blank=True, null=True, verbose_name='Camarim')),
                ('catering', models.TextField(blank=True, null=True, verbose_name='Alimentação')),
                ('wardrobe', models.TextField(blank=True, null=True, verbose_name='Figurino')),
                ('internal_notes', models.TextField(blank=True, help_text='Visível apenas para a produção.', null=True, verbose_name='Observações Internas')),
                ('band_notes', models.TextField(blank=True, help_text='Visível para todos os integrantes.', null=True, verbose_name='Observações para a Banda')),
            ],
            options={
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
                'ordering': ['date', 'show_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('PRODUTOR', 'Produtor'), ('INTEGRANTE', 'Integrante')], default='INTEGRANTE', max_length=20, verbose_name='Perfil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
