# Generated by Django 6.0.6 on 2026-07-01 04:52

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Do que se trata?')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('file', models.FileField(upload_to=core.models.receipt_upload_path, verbose_name='Arquivo / Comprovante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.show')),
            ],
            options={
                'verbose_name': 'Comprovante Financeiro',
                'verbose_name_plural': 'Comprovantes Financeiros',
                'ordering': ['-created_at'],
            },
        ),
    ]
