# Generated by Django 6.0.6 on 2026-07-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_financialreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='location_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Localização'),
        ),
    ]
