# Generated by Django 6.0.6 on 2026-07-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_show_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='backline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Backline'),
        ),
        migrations.AddField(
            model_name='show',
            name='backline_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato (Backline)'),
        ),
        migrations.AddField(
            model_name='show',
            name='led_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato (LED)'),
        ),
        migrations.AddField(
            model_name='show',
            name='led_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sistema de LED'),
        ),
        migrations.AddField(
            model_name='show',
            name='lighting_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato (Luz)'),
        ),
        migrations.AddField(
            model_name='show',
            name='lighting_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sistema de Iluminação'),
        ),
        migrations.AddField(
            model_name='show',
            name='pyrotechnics',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Efeitos Pirotecnia'),
        ),
        migrations.AddField(
            model_name='show',
            name='pyrotechnics_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato (Pirotecnia)'),
        ),
        migrations.AddField(
            model_name='show',
            name='sound_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato (Som)'),
        ),
        migrations.AddField(
            model_name='show',
            name='sound_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sistema de Sonorização'),
        ),
    ]
