# Generated by Django 6.0.6 on 2026-07-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_show_backline_show_backline_contact_show_led_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='attractions',
            field=models.TextField(blank=True, null=True, verbose_name='Outras Atrações'),
        ),
        migrations.AlterField(
            model_name='show',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='show',
            name='venue',
            field=models.CharField(max_length=200, verbose_name='Local do Show'),
        ),
    ]
