# Generated by Django 6.0.6 on 2026-07-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_show_attractions_alter_show_address_alter_show_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='generator_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato (Gerador)'),
        ),
        migrations.AddField(
            model_name='show',
            name='generator_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gerador'),
        ),
        migrations.AddField(
            model_name='show',
            name='loaders_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato (Carregadores)'),
        ),
        migrations.AddField(
            model_name='show',
            name='loaders_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Carregadores'),
        ),
    ]
