# Generated by Django 6.0.6 on 2026-07-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_show_generator_contact_show_generator_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='show_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário Final do Show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Duração do Show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Início do Show'),
        ),
    ]
