# Generated by Django 6.0.6 on 2026-07-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_show_show_end_time_alter_show_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='duration',
            field=models.CharField(blank=True, help_text='Ex: 2 horas', max_length=50, null=True, verbose_name='Duração do Show'),
        ),
    ]
