# Generated by Django 6.0.6 on 2026-07-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_show_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='accommodation_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Localização da Hospedagem'),
        ),
    ]
