# Generated by Django 6.0.6 on 2026-07-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_show_accommodation_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='shows/documentos/', verbose_name='Anexar Documentos'),
        ),
    ]
