# Generated by Django 6.0.6 on 2026-07-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_show_transport_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='accommodation_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato (Hospedagem)'),
        ),
    ]
