# Generated by Django 6.0.6 on 2026-07-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_show_transfer_show_transfer_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='dressing_room_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato (Camarim)'),
        ),
    ]
