# Generated by Django 6.0.6 on 2026-07-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_show_dressing_room_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='transfer_contact',
        ),
    ]
