# Generated by Django 6.0.6 on 2026-07-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_show_transfer_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='transfer',
            field=models.TextField(blank=True, null=True, verbose_name='Baldeação'),
        ),
    ]
