# Generated by Django 6.0.6 on 2026-07-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_show_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='transfer',
            field=models.TextField(blank=True, null=True, verbose_name='Palco/Baldeação'),
        ),
    ]
