# Generated by Django 6.0.6 on 2026-07-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_show_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='transfer_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato (Palco/Baldeação)'),
        ),
    ]
