# Generated by Django 6.0.6 on 2026-07-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_show_transfer_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='local_production',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Produção Local'),
        ),
        migrations.AddField(
            model_name='show',
            name='local_production_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato (Produção Local)'),
        ),
    ]
