# Generated by Django 6.0.6 on 2026-07-01 06:40

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_show_local_production_show_local_production_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='contract_file',
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição do Documento')),
                ('file', models.FileField(upload_to=core.models.contract_upload_path, verbose_name='Arquivo / Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.show')),
            ],
            options={
                'verbose_name': 'Documento Anexado',
                'verbose_name_plural': 'Documentos Anexados',
                'ordering': ['-created_at'],
            },
        ),
    ]
