# Generated by Django 6.0.6 on 2026-07-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_show_contract_file_contractdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Documento Anexado', 'verbose_name_plural': 'Documentos Anexados (Apenas Produção)'},
        ),
        migrations.AlterModelOptions(
            name='financialreceipt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comprovante Financeiro', 'verbose_name_plural': 'Comprovantes Financeiros (Apenas Produção)'},
        ),
        migrations.AddField(
            model_name='show',
            name='event_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Evento'),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nome do Show'),
        ),
    ]
