# Generated by Django 6.0.6 on 2026-07-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_contractdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='venue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local do Show'),
        ),
    ]
