# Generated by Django 6.0.6 on 2026-07-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_show_city_alter_show_date_alter_show_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='departure_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local de Saída'),
        ),
    ]
