# Generated by Django 6.0.6 on 2026-07-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_show_departure_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='departure_location_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Localização'),
        ),
    ]
