# Generated by Django 6.0.6 on 2026-07-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_show_departure_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='distance_km',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kilometragem'),
        ),
        migrations.AddField(
            model_name='show',
            name='travel_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempo de Viagem'),
        ),
        migrations.AlterField(
            model_name='show',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Chegada'),
        ),
        migrations.AlterField(
            model_name='show',
            name='soundcheck_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Passagem de Som'),
        ),
    ]
