# Generated by Django 6.0.6 on 2026-07-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_show_distance_km_show_travel_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='travel_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempo de Deslocamento'),
        ),
    ]
