# Generated by Django 6.0.6 on 2026-07-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_show_travel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Final do Show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Início do Show'),
        ),
    ]
