# Generated by Django 6.0.6 on 2026-07-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_show_show_end_time_alter_show_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='distance_km',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distância'),
        ),
    ]
