# Generated by Django 6.0.6 on 2026-07-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_show_distance_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Previsão Chegada'),
        ),
        migrations.AlterField(
            model_name='show',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário Saída'),
        ),
    ]
