# Generated by Django 6.0.6 on 2026-07-03 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_show_arrival_time_alter_show_departure_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Banda')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (URL)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bands/logos/', verbose_name='Logo da Banda')),
            ],
            options={
                'verbose_name': 'Banda',
                'verbose_name_plural': 'Bandas',
            },
        ),
        migrations.AddField(
            model_name='show',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='core.band', verbose_name='Banda'),
        ),
        migrations.AddField(
            model_name='user',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.band', verbose_name='Banda'),
        ),
    ]
