# Generated by Django 6.0.6 on 2026-07-03 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_band_show_band_user_band'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('contact_type', models.CharField(choices=[('FORNECEDOR', 'Fornecedor'), ('CONTRATANTE', 'Contratante'), ('ESTABELECIMENTO', 'Estabelecimento/Casa de Show'), ('TECNICO', 'Técnico/Freelancer'), ('OUTRO', 'Outro')], default='FORNECEDOR', max_length=50, verbose_name='Tipo')),
                ('contact_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contato (Telefone/E-mail)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.band', verbose_name='Banda')),
            ],
            options={
                'verbose_name': 'Contato (Banco de Dados)',
                'verbose_name_plural': 'Banco de Dados',
                'ordering': ['name'],
            },
        ),
    ]
