# Generated by Django 6.0.6 on 2026-07-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_user_options_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contato (Telefone)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('FORNECEDOR', 'Fornecedor (a)'), ('CONTRATANTE', 'Contratante'), ('ESTABELECIMENTO', 'Estabelecimento'), ('RESTAURANTE', 'Restaurante'), ('HOSPEDAGEM', 'Hospedagem'), ('PRODUTOR', 'Produtor (a)')], default='FORNECEDOR', max_length=50, verbose_name='Tipo'),
        ),
    ]
