# Generated by Django 6.0.6 on 2026-07-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_contact_contact_info_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque para suspender totalmente o acesso desta banda ao sistema.', verbose_name='Acesso Liberado (Ativo)'),
        ),
        migrations.AddField(
            model_name='band',
            name='subscription_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='band',
            name='subscription_plan',
            field=models.CharField(choices=[('MENSAL', 'Mensal'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSAL', max_length=20, verbose_name='Plano de Assinatura'),
        ),
        migrations.AddField(
            model_name='band',
            name='subscription_status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status do Pagamento'),
        ),
    ]
