# Generated by Django 6.0.6 on 2026-07-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_band_is_active_band_subscription_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='airline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa Aérea (Aéreo)'),
        ),
        migrations.AddField(
            model_name='show',
            name='flight_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Voo (Aéreo)'),
        ),
    ]
