# Generated by Django 6.0.6 on 2026-07-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_show_airline_show_flight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Previsão Chegada'),
        ),
        migrations.AlterField(
            model_name='show',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Horário Saída'),
        ),
    ]
