# Generated by Django 6.0.6 on 2026-07-08 20:07

from django.db import migrations, models
import datetime
from django.utils import timezone

def convert_time_to_datetime(apps, schema_editor):
    Show = apps.get_model('core', 'Show')
    for show in Show.objects.all():
        if show.date:
            if show.arrival_time:
                # If it's already a datetime (e.g. from local sqlite that already migrated) we just use it, otherwise we combine.
                if isinstance(show.arrival_time, datetime.time):
                    dt = datetime.datetime.combine(show.date, show.arrival_time)
                    show.arrival_time_tmp = timezone.make_aware(dt) if timezone.is_naive(dt) else dt
                else:
                    show.arrival_time_tmp = show.arrival_time

            if show.departure_time:
                if isinstance(show.departure_time, datetime.time):
                    dt = datetime.datetime.combine(show.date, show.departure_time)
                    show.departure_time_tmp = timezone.make_aware(dt) if timezone.is_naive(dt) else dt
                else:
                    show.departure_time_tmp = show.departure_time
            show.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_show_airline_show_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='arrival_time_tmp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='departure_time_tmp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            convert_time_to_datetime,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='show',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='show',
            name='departure_time',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='arrival_time_tmp',
            new_name='arrival_time',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='departure_time_tmp',
            new_name='departure_time',
        ),
        migrations.AlterField(
            model_name='show',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Previsão Chegada'),
        ),
        migrations.AlterField(
            model_name='show',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Horário Saída'),
        ),
    ]
