# Generated by Django 6.0.6 on 2026-07-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_show_arrival_time_alter_show_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='contract_type',
            field=models.CharField(blank=True, help_text='Ex: Prefeitura, Empresário, Bilheteria, etc.', max_length=100, null=True, verbose_name='Tipo de Contratação'),
        ),
    ]
