# Generated by Django 6.0.6 on 2026-07-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='address_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Localização'),
        ),
    ]
