# Generated by Django 6.0.6 on 2026-07-10 12:21

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_show_address_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('PRE_RESERVADO', 'Reserva'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='PRE_RESERVADO', max_length=30, verbose_name='Status do Show'),
        ),
        migrations.CreateModel(
            name='ShowPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição (Ex: Sinal, Parcela 2)')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Data Prevista')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('payment_method', models.CharField(choices=[('PIX', 'Pix'), ('TRANSFERENCIA', 'Transferência'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('BOLETO', 'Boleto'), ('CHEQUE', 'Cheque'), ('OUTRO', 'Outro')], default='PIX', max_length=50, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=30, verbose_name='Status')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.payment_upload_path, verbose_name='Arquivo / Comprovante')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.show')),
            ],
            options={
                'verbose_name': 'Recebimento',
                'verbose_name_plural': 'Recebimentos do Show (Apenas Produção)',
                'ordering': ['expected_date', '-created_at'],
            },
        ),
    ]
