# Generated by Django 6.0.6 on 2026-07-10 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_show_status_showpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTeamCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Integrante / Função')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=30, verbose_name='Status de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_team_costs', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_costs', to='core.show')),
            ],
            options={
                'verbose_name': 'Custo com Equipe',
                'verbose_name_plural': 'Custos com Equipe (Apenas Produção)',
                'ordering': ['name'],
            },
        ),
    ]
