# Generated by Django 6.0.6 on 2026-07-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_showteamcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showteamcost',
            name='status',
        ),
        migrations.AddField(
            model_name='showteamcost',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='showteamcost',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome do Integrante'),
        ),
    ]
