# Generated by Django 6.0.6 on 2026-07-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_showteamcost_status_showteamcost_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreceipt',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='financialreceipt',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
