# Generated by Django 6.0.6 on 2026-07-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_financialreceipt_category_financialreceipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='showteamcost',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
