# Generated by Django 6.0.6 on 2026-07-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_showteamcost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showpayment',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='RECEBIDO', max_length=30, verbose_name='Status'),
        ),
    ]
