# Generated by Django 6.0.6 on 2026-07-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_showpayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local'),
        ),
    ]
