# Generated by Django 6.0.6 on 2026-07-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_contact_link_contact_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='technical_file',
            field=models.FileField(blank=True, null=True, upload_to='shows/tecnica/', verbose_name='Documento Técnico'),
        ),
    ]
