# Generated by Django 6.0.6 on 2026-07-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_show_technical_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='technical_file',
        ),
    ]
