# Generated by Django 6.0.6 on 2026-07-14 13:34

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_show_technical_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Mensal', max_length=100, verbose_name='Nome do Plano')),
                ('billing_cycle', models.CharField(choices=[('MENSAL', 'Mensal'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual'), ('PERSONALIZADO', 'Personalizado')], default='MENSAL', max_length=20, verbose_name='Ciclo de Cobrança')),
                ('contracted_value', models.DecimalField(decimal_places=2, default=300.0, max_digits=10, verbose_name='Valor Contratado')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Próximo Vencimento')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('VENCENDO', 'Vencendo'), ('VENCIDO', 'Vencido'), ('SUSPENSO', 'Suspenso'), ('TESTE', 'Teste'), ('CANCELADO', 'Cancelado')], default='TESTE', max_length=20, verbose_name='Status da Assinatura')),
                ('payment_method_preference', models.CharField(choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão'), ('TRANSFERENCIA', 'Transferência'), ('DINHEIRO', 'Dinheiro'), ('OUTRO', 'Outro')], default='PIX', max_length=50, verbose_name='Preferência de Pagamento')),
                ('financial_responsible_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsável Financeiro')),
                ('billing_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone de Cobrança (WhatsApp)')),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Cobrança')),
                ('internal_notes', models.TextField(blank=True, null=True, verbose_name='Observações Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('band', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.band', verbose_name='Banda')),
            ],
            options={
                'verbose_name': 'Assinatura SaaS',
                'verbose_name_plural': 'Assinaturas SaaS',
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_period', models.CharField(max_length=100, verbose_name='Período de Referência (Ex: Agosto/2026)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Cobrado')),
                ('due_date', models.DateField(verbose_name='Vencimento da Fatura')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado'), ('ISENTO', 'Isento')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(blank=True, choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartão'), ('TRANSFERENCIA', 'Transferência'), ('DINHEIRO', 'Dinheiro'), ('OUTRO', 'Outro')], max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to=core.models.billing_proof_upload_path, verbose_name='Comprovante')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='core.band', verbose_name='Banda')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billings', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.bandsubscription', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Fatura SaaS',
                'verbose_name_plural': 'Faturas SaaS',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
