# Generated by Django 6.0.6 on 2026-07-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_bandsubscription_billingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='boarding_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Embarque'),
        ),
        migrations.AddField(
            model_name='show',
            name='checkout_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Saída Hospedagem'),
        ),
    ]
