# Generated by Django 6.0.6 on 2026-07-16 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_show_boarding_time_show_checkout_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('NEW_SHOW', 'Novo show'), ('SHOW_CANCELLED', 'Show cancelado'), ('SHOW_DATE_CHANGED', 'Data do show alterada'), ('SHOW_START_TIME_CHANGED', 'Horário inicial do show alterado')], max_length=50, verbose_name='Tipo de Evento')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('target_url', models.CharField(max_length=500, verbose_name='URL de Destino')),
                ('event_key', models.CharField(max_length=255, verbose_name='Chave de Idempotência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_as_actor', to=settings.AUTH_USER_MODEL, verbose_name='Ator')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.band', verbose_name='Banda')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('related_show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.show', verbose_name='Show Relacionado')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'band', 'read_at', 'created_at'], name='core_notifi_recipie_b0fb50_idx'), models.Index(fields=['band', 'created_at'], name='core_notifi_band_id_567b5f_idx')],
                'constraints': [models.UniqueConstraint(fields=('band', 'recipient', 'event_key'), name='unique_notification_recipient_event')],
            },
        ),
    ]
