# Generated by Django 6.0.6 on 2026-07-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='notification_revision',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
