# Generated by Django 6.0.6 on 2026-07-17 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_show_notification_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(verbose_name='Endpoint')),
                ('endpoint_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Hash do Endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='Chave Pública P256DH')),
                ('auth', models.CharField(max_length=255, verbose_name='Chave de Autenticação')),
                ('service_worker_scope', models.CharField(max_length=500, verbose_name='Scope do Service Worker')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='User Agent')),
                ('expiration_time', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('failure_count', models.PositiveSmallIntegerField(default=0, verbose_name='Contagem de Falhas')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Sucesso')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Falha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to='core.band', verbose_name='Banda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Inscrição Web Push',
                'verbose_name_plural': 'Inscrições Web Push',
                'indexes': [models.Index(fields=['user', 'band', 'is_active'], name='core_webpus_user_id_f5cdf0_idx'), models.Index(fields=['band', 'is_active'], name='core_webpus_band_id_721255_idx')],
            },
        ),
    ]
