# Generated by Django 6.0.6 on 2026-07-17 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_webpushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SENDING', 'Enviando'), ('SENT', 'Enviado'), ('TEMPORARY_FAILURE', 'Falha Temporária'), ('PERMANENT_FAILURE', 'Falha Permanente'), ('SKIPPED', 'Ignorado')], default='PENDING', max_length=50, verbose_name='Status')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas')),
                ('last_http_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Último Status HTTP')),
                ('error_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Código de Erro')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Tentativa')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_deliveries', to='core.notification', verbose_name='Notificação')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.webpushsubscription', verbose_name='Inscrição Web Push')),
            ],
            options={
                'verbose_name': 'Entrega Web Push',
                'verbose_name_plural': 'Entregas Web Push',
                'indexes': [models.Index(fields=['status', 'updated_at'], name='core_webpus_status_b0c1b5_idx'), models.Index(fields=['notification', 'status'], name='core_webpus_notific_f2d91c_idx')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'subscription'), name='uniq_wp_delivery_notif_sub')],
            },
        ),
    ]
