# Generated by Django 6.0.6 on 2026-07-19 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_webpushdelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushOperationalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global'), ('BAND', 'Banda')], max_length=20)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('RESOLVED', 'Resolvido')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recommended_action', models.TextField(blank=True)),
                ('current_count', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=1)),
                ('first_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='web_push_operational_alerts', to='core.band')),
            ],
            options={
                'verbose_name': 'Alerta Operacional Web Push',
                'verbose_name_plural': 'Alertas Operacionais Web Push',
                'indexes': [models.Index(fields=['status', 'severity'], name='core_webpus_status_70cea3_idx'), models.Index(fields=['band', 'status'], name='core_webpus_band_id_fc75d0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('scope_type', 'GLOBAL'), ('band__isnull', True)), models.Q(('scope_type', 'BAND'), ('band__isnull', False)), _connector='OR'), name='wp_alert_scope_band_consistency'), models.CheckConstraint(condition=models.Q(('current_count__gte', 0)), name='wp_alert_current_count_gte_zero'), models.CheckConstraint(condition=models.Q(('opened_count__gte', 1)), name='wp_alert_opened_count_gte_one'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'ACTIVE'), ('resolved_at__isnull', True)), models.Q(('status', 'RESOLVED'), ('resolved_at__isnull', False)), _connector='OR'), name='wp_alert_status_resolved_at_consistency')],
            },
        ),
    ]
