# Generated by Django 6.0.6 on 2026-07-21 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_webpushoperationalalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushOperationalAlertCycleLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='web_push_operational_alert_cycle', max_length=100, unique=True)),
                ('owner_token', models.CharField(max_length=255)),
                ('locked_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'web_push_operational_alert_cycle_lease',
            },
        ),
        migrations.CreateModel(
            name='WebPushOperationalAlertEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('OPENED', 'Opened'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved')], max_length=20)),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('severity_snapshot', models.CharField(max_length=50)),
                ('scope_type_snapshot', models.CharField(max_length=20)),
                ('band_slug_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('code_snapshot', models.CharField(max_length=100)),
                ('current_count_snapshot', models.IntegerField()),
                ('opened_count_snapshot', models.IntegerField()),
                ('recipient_set_hash', models.CharField(max_length=255)),
                ('recipient_count', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('TEMPORARY_FAILURE', 'Temporary Failure'), ('PERMANENT_FAILURE', 'Permanent Failure'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=30)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_deliveries', to='core.webpushoperationalalert')),
            ],
            options={
                'db_table': 'web_push_operational_alert_email_delivery',
                'constraints': [models.CheckConstraint(condition=models.Q(('recipient_count__gte', 1)), name='wp_alert_email_recip_gte_one'), models.CheckConstraint(condition=models.Q(('attempt_count__gte', 0)), name='wp_alert_email_attempt_gte_zero'), models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='wp_alert_email_max_attempts_gte_one'), models.CheckConstraint(condition=models.Q(('attempt_count__lte', models.F('max_attempts'))), name='wp_alert_email_attempt_lte_max'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'SENT'), ('sent_at__isnull', False)), models.Q(models.Q(('status', 'SENT'), _negated=True), ('sent_at__isnull', True)), _connector='OR'), name='wp_alert_email_status_sent_at')],
            },
        ),
    ]
