# Generated by Django 6.0.6 on 2026-07-22 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_webpushoperationalalertcyclelease_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandDashboardPendingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_pending_items', to='core.band')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_pending_items_created', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_pending_items', to='core.show')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
