# Generated by Django 6.0.6 on 2026-07-22 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_banddashboardpendingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeBandNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('band', models.ForeignKey(blank=True, help_text='Deixe em branco para enviar a todas as bandas (Todos).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrative_notices', to='core.band', verbose_name='Banda Destino')),
            ],
            options={
                'verbose_name': 'Aviso Administrativo',
                'verbose_name_plural': 'Avisos Administrativos',
                'ordering': ['-created_at'],
            },
        ),
    ]
