# Generated by Django 6.0.6 on 2026-07-22 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_administrativebandnotice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativebandnotice',
            name='title',
        ),
        migrations.AddField(
            model_name='administrativebandnotice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_administrative_notices', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='administrativebandnotice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio'),
        ),
    ]
