# Generated by Django 6.0.6 on 2026-07-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_administrativebandnotice_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='soundcheck_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Final da passagem de som'),
        ),
    ]
