# Generated by Django 6.0.6 on 2026-07-24 18:15

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='android_installation_guide_image',
            field=models.ImageField(blank=True, null=True, upload_to='app_install_guides/android/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp']), core.models.validate_image_size], verbose_name='Guia de Instalação Android'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ios_installation_guide_image',
            field=models.ImageField(blank=True, null=True, upload_to='app_install_guides/ios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp']), core.models.validate_image_size], verbose_name='Guia de Instalação iOS'),
        ),
    ]
