# Generated by Django 6.0.6 on 2026-07-25 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_systemsettings_android_installation_guide_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banddashboardpendingitem',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_pending_items', to='core.show'),
        ),
    ]
