# Generated by Django 6.0.6 on 2026-07-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('NEW_SHOW', 'Novo show'), ('SHOW_CANCELLED', 'Show cancelado'), ('SHOW_DATE_CHANGED', 'Data do show alterada'), ('SHOW_START_TIME_CHANGED', 'Horário inicial do show alterado'), ('SHOW_CONFIRMED', 'Show confirmado')], max_length=50, verbose_name='Tipo de Evento'),
        ),
    ]
