# Generated by Django 6.0.6 on 2026-07-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_notification_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageBandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da banda ou artista')),
                ('image', models.ImageField(upload_to='landing/band_logos/', verbose_name='Logomarca')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logo da Landing Page',
                'verbose_name_plural': 'Logos da Landing Page',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
