# Generated by Django 6.0.6 on 2026-07-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_landingpagebandlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagebandlogo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
