# Generated by Django 6.0.6 on 2026-07-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_riderdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='banddashboardpendingitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
