# Generated by Django 6.0.6 on 2026-07-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_banddashboardpendingitem_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('role', models.CharField(max_length=150, verbose_name='Função')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF')),
                ('vehicle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Veículo')),
                ('category', models.CharField(choices=[('PRODUCAO', 'Produção'), ('MUSICO', 'Músico'), ('EQUIPE_TECNICA', 'Equipe Técnica'), ('SERVICOS', 'Serviços')], max_length=50, verbose_name='Categoria')),
                ('pix_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave-Pix')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='core.band')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'ordering': ['order', 'id'],
            },
        ),
    ]
