# Generated by Django 6.0.6 on 2026-07-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_integrante'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='birth_date',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='miles_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Milhas'),
        ),
    ]
