# Generated by Django 6.0.6 on 2026-08-03 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_integrante_birth_date_integrante_miles_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('band', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lodging_template', to='core.band')),
            ],
        ),
        migrations.CreateModel(
            name='RoomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('reservation_code', models.CharField(blank=True, max_length=100, null=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADA', 'Publicada'), ('ARQUIVADA', 'Arquivada')], default='RASCUNHO', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_to_hotel_at', models.DateTimeField(blank=True, null=True)),
                ('content_revision', models.PositiveBigIntegerField(default=1)),
                ('last_sent_revision', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_room_lists', to=settings.AUTH_USER_MODEL)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_lists', to='core.band')),
                ('last_sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_room_lists', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_room_lists', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_lists', to='core.show')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_or_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CASAL', 'Casal'), ('DUPLO', 'Duplo'), ('TRIPLO', 'Triplo'), ('QUADRUPLO', 'Quádruplo'), ('PERSONALIZADO', 'Personalizado')], max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('beds_config', models.CharField(blank=True, max_length=255, null=True)),
                ('has_ac', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.roomlist')),
            ],
        ),
        migrations.CreateModel(
            name='RoomListParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_lodging', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('snapshot_name', models.CharField(max_length=255)),
                ('snapshot_cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('snapshot_role', models.CharField(blank=True, max_length=150, null=True)),
                ('snapshot_category', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_integrante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_participations', to='core.integrante')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='core.room')),
                ('room_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.roomlist')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CASAL', 'Casal'), ('DUPLO', 'Duplo'), ('TRIPLO', 'Triplo'), ('QUADRUPLO', 'Quádruplo'), ('PERSONALIZADO', 'Personalizado')], max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('beds_config', models.CharField(blank=True, max_length=255, null=True)),
                ('has_ac', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.lodgingtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_participations', to='core.integrante')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.lodgingtemplate')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.templateroom')),
            ],
        ),
        migrations.AddIndex(
            model_name='roomlist',
            index=models.Index(fields=['band', 'status'], name='core_roomli_band_id_a3305e_idx'),
        ),
        migrations.AddIndex(
            model_name='roomlist',
            index=models.Index(fields=['show', 'status'], name='core_roomli_show_id_3eb2bd_idx'),
        ),
        migrations.AddIndex(
            model_name='roomlist',
            index=models.Index(fields=['band', 'check_in'], name='core_roomli_band_id_aadff3_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomlist',
            constraint=models.CheckConstraint(condition=models.Q(('content_revision__gte', 1)), name='content_revision_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='roomlist',
            constraint=models.CheckConstraint(condition=models.Q(('last_sent_revision__lte', models.F('content_revision')), ('last_sent_revision__isnull', True), _connector='OR'), name='last_sent_rev_lte_content_rev'),
        ),
        migrations.AddConstraint(
            model_name='roomlist',
            constraint=models.CheckConstraint(condition=models.Q(('last_sent_revision__isnull', True), ('last_sent_to_hotel_at__isnull', False), _connector='OR'), name='last_sent_rev_requires_date'),
        ),
        migrations.AddConstraint(
            model_name='roomlist',
            constraint=models.CheckConstraint(condition=models.Q(('check_in__isnull', True), ('check_out__isnull', True), ('check_out__gt', models.F('check_in')), _connector='OR'), name='check_out_gt_check_in'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_list', 'order'], name='core_room_room_li_5b6cb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('room_list', 'number_or_name'), name='unique_room_number_per_list'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='room_capacity_gt_0'),
        ),
        migrations.AddIndex(
            model_name='roomlistparticipant',
            index=models.Index(fields=['room_list', 'room'], name='core_roomli_room_li_72be12_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomlistparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('original_integrante__isnull', False)), fields=('room_list', 'original_integrante'), name='unique_integrante_per_room_list'),
        ),
        migrations.AddIndex(
            model_name='templateroom',
            index=models.Index(fields=['template', 'order'], name='core_templa_templat_a2798e_idx'),
        ),
        migrations.AddConstraint(
            model_name='templateroom',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='template_room_capacity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='templateparticipant',
            constraint=models.UniqueConstraint(fields=('template', 'original_integrante'), name='unique_integrante_per_template'),
        ),
    ]
