# Generated by Django 6.0.6 on 2026-08-03 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_lodgingtemplate_roomlist_room_roomlistparticipant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='is_active',
            field=models.BooleanField(default=True, db_index=True, verbose_name='Ativo'),
        ),
        migrations.CreateModel(
            name='ShowParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_participations', to='core.integrante')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.show')),
            ],
            options={
                'verbose_name': 'Escala de Integrante',
                'verbose_name_plural': 'Escalas de Integrantes',
                'ordering': ['integrante__order', 'integrante__name', 'integrante_id'],
                'constraints': [models.UniqueConstraint(fields=('show', 'integrante'), name='unique_integrante_per_show')],
            },
        ),
    ]
