# Generated by Django 6.0.6 on 2026-08-18 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_add_show_participant_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_shared_globally',
            field=models.BooleanField(default=False, verbose_name='Compartilhado globalmente'),
        ),
        migrations.AddField(
            model_name='contact',
            name='normalized_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='public_information',
            field=models.TextField(blank=True, null=True, verbose_name='Informações públicas'),
        ),
        migrations.AddField(
            model_name='contact',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Compartilhado em'),
        ),
        migrations.AddField(
            model_name='contact',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhado por'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_shared_globally', True), ('normalized_phone__isnull', False), models.Q(('normalized_phone', ''), _negated=True)), fields=('normalized_phone',), name='unique_global_phone'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_shared_globally', True), ('normalized_email__isnull', False), models.Q(('normalized_email', ''), _negated=True)), fields=('normalized_email',), name='unique_global_email'),
        ),
    ]
