# Generated by Django 6.0.6 on 2026-08-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_contact_is_shared_globally_contact_normalized_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PRODUTOR', 'Produtor'), ('EMPRESARIO', 'Empresário'), ('INTEGRANTE', 'Integrante')], default='INTEGRANTE', max_length=20, verbose_name='Perfil'),
        ),
    ]
