# Generated by Django 6.0.6 on 2026-08-19 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('scheduled_at', models.DateTimeField(verbose_name='Agendado para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='core.band', verbose_name='Banda')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_band_notices', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Aviso da Banda',
                'verbose_name_plural': 'Avisos da Banda',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sent_at', 'scheduled_at'], name='core_bandno_sent_at_0a4461_idx')],
            },
        ),
    ]
