# Generated by Django 6.0.6 on 2026-08-20 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_bandnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='billing_cycle',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ciclo na Época'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='plan_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Plano na Época'),
        ),
        migrations.AlterUniqueTogether(
            name='billingrecord',
            unique_together={('subscription', 'due_date')},
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fornecedor / Beneficiário')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('competence_date', models.DateField(verbose_name='Data de Competência')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pagamento')),
                ('internal_notes', models.TextField(blank=True, null=True, verbose_name='Observações Internas')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='expenses_proofs/', verbose_name='Comprovante')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Despesa Recorrente?')),
                ('recurrence_cycle', models.CharField(blank=True, choices=[('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=20, null=True, verbose_name='Ciclo da Recorrência')),
                ('recurrence_end_date', models.DateField(blank=True, null=True, verbose_name='Data Final da Recorrência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_expenses', to='core.expense', verbose_name='Despesa de Origem')),
            ],
            options={
                'verbose_name': 'Despesa Administrativa',
                'verbose_name_plural': 'Despesas Administrativas',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
