# Generated by Django 6.0.6 on 2026-08-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_billingrecord_billing_cycle_billingrecord_plan_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandsubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Assinatura SaaS', 'verbose_name_plural': 'Assinaturas SaaS'},
        ),
        migrations.AddField(
            model_name='bandsubscription',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AddField(
            model_name='bandsubscription',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Excluída'),
        ),
        migrations.AlterField(
            model_name='bandsubscription',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativa'), ('DESATIVADO', 'Desativada')], default='ATIVO', max_length=20, verbose_name='Status da Assinatura'),
        ),
    ]
