# Generated by Django 6.0.6 on 2026-08-21 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_bandsubscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandsubscription',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.band', verbose_name='Banda'),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('ISENTO', 'Isento')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
    ]
