# Generated by Django 6.0.6 on 2026-08-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_bandsubscription_band_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandsubscription',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='Renovar automaticamente'),
        ),
    ]
