# Generated by Django 6.0.6 on 2026-08-21 17:34

import core.file_policy
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_bandsubscription_auto_renew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='bands/logos/', validators=[core.file_policy.validate_file_size_and_type], verbose_name='Logo da Banda'),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.billing_proof_upload_path, validators=[core.file_policy.validate_file_size_and_type], verbose_name='Comprovante'),
        ),
        migrations.AlterField(
            model_name='contractdocument',
            name='file',
            field=models.FileField(upload_to=core.models.contract_upload_path, validators=[core.file_policy.validate_file_size_and_type], verbose_name='Arquivo / Documento'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='expenses_proofs/', validators=[core.file_policy.validate_file_size_and_type], verbose_name='Comprovante'),
        ),
        migrations.AlterField(
            model_name='financialreceipt',
            name='file',
            field=models.FileField(upload_to=core.models.receipt_upload_path, validators=[core.file_policy.validate_file_size_and_type], verbose_name='Arquivo / Comprovante'),
        ),
        migrations.AlterField(
            model_name='landingpagebandlogo',
            name='image',
            field=models.ImageField(upload_to='landing/band_logos/', validators=[core.file_policy.validate_file_size_and_type], verbose_name='Logomarca'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(upload_to='partners/logos/', validators=[core.file_policy.validate_file_size_and_type], verbose_name='Logomarca ou Imagem'),
        ),
        migrations.AlterField(
            model_name='riderdocument',
            name='file',
            field=models.FileField(upload_to=core.models.rider_upload_path, validators=[core.file_policy.validate_file_size_and_type], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='showpayment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.payment_upload_path, validators=[core.file_policy.validate_file_size_and_type], verbose_name='Arquivo / Comprovante'),
        ),
        migrations.AlterField(
            model_name='supportticketattachment',
            name='file',
            field=models.FileField(upload_to=core.models.support_ticket_attachment_path, validators=[core.file_policy.validate_file_size_and_type]),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='system_logos/', validators=[core.file_policy.validate_file_size_and_type]),
        ),
    ]
