# Generated by Django 6.0.6 on 2026-08-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_band_logo_alter_billingrecord_proof_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateroom',
            name='number_or_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número ou Nome'),
        ),
    ]
