# Generated by Django 6.0.6 on 2026-08-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_templateroom_number_or_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='plan_type',
            field=models.CharField(choices=[('BASICO', 'Básico'), ('AVANCADO', 'Avançado')], default='AVANCADO', max_length=15, verbose_name='Plano da banda'),
        ),
    ]
