# Generated by Django 6.0.6 on 2026-08-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_band_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingtemplate',
            name='default_observations',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='roomlist',
            name='observations',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
