# Generated by Django 6.0.6 on 2026-08-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_lodgingtemplate_default_observations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Oculto pelo Administrador'),
        ),
    ]
