# Generated by Django 6.0.6 on 2026-08-29 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_add_contact_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_contacts', to='core.contact', verbose_name='Copiado de'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('copied_from__isnull', False)), fields=('band', 'copied_from'), name='unique_contact_copy_per_band'),
        ),
    ]
