# Generated by Django 6.0.6 on 2026-08-29 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_contact_copied_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Curtida')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_likes', to='core.band', verbose_name='Banda do Produtor')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.contact', verbose_name='Contato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_likes', to=settings.AUTH_USER_MODEL, verbose_name='Produtor')),
            ],
            options={
                'verbose_name': 'Curtida de Contato',
                'verbose_name_plural': 'Curtidas de Contatos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('contact', 'user'), name='unique_contact_like_per_user')],
            },
        ),
    ]
