# Generated by Django 6.0.6 on 2026-08-29 21:50

import core.file_policy
import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_contactlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Solicitação')),
                ('date', models.DateField(verbose_name='Data do Show')),
                ('time', models.TimeField(verbose_name='Horário do Show')),
                ('contact', models.CharField(max_length=200, verbose_name='Contato')),
                ('normalized_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contato Normalizado')),
                ('origin', models.CharField(max_length=200, verbose_name='Origem')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Cachê (R$)')),
                ('phase', models.CharField(choices=[('RESERVA', 'Reserva'), ('FECHADO', 'Fechado'), ('DESISTENCIA', 'Desistência')], db_index=True, default='RESERVA', max_length=20, verbose_name='Fase do Orçamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_proposals', to='core.band', verbose_name='Banda')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commercial_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('show', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_proposal', to='core.show', verbose_name='Show Vinculado')),
            ],
            options={
                'verbose_name': 'Solicitação Comercial',
                'verbose_name_plural': 'Solicitações Comerciais',
                'ordering': ['date', 'time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommercialProposalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.commercial_proposal_document_upload_path, validators=[core.file_policy.validate_file_size_and_type], verbose_name='Arquivo')),
                ('original_name', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.commercialproposal', verbose_name='Solicitação')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_commercial_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento Comercial',
                'verbose_name_plural': 'Documentos Comerciais',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commercialproposal',
            index=models.Index(fields=['band', 'phase', 'date'], name='idx_commercial_band_phase_date'),
        ),
    ]
