# Generated by Django 6.0.6 on 2026-08-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_commercialproposal_commercialproposaldocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialproposal',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='commercialproposal',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Cachê (R$)'),
        ),
        migrations.AlterField(
            model_name='commercialproposal',
            name='origin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='commercialproposal',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário do Show'),
        ),
    ]
