# Generated by Django 6.0.6 on 2026-08-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_alter_commercialproposal_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('HOSPEDAGEM', 'Hotel'), ('RESTAURANTE', 'Restaurante'), ('ESTABELECIMENTO', 'Empresa'), ('FORNECEDOR', 'Fornecedor'), ('PRODUTOR', 'Produtor(a)'), ('CONTRATANTE', 'Contratante')], default='FORNECEDOR', max_length=50, verbose_name='Tipo'),
        ),
    ]
