# Generated by Django 6.0.6 on 2026-08-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_contact_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='checkout_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Saída p/ Show'),
        ),
    ]
