# Generated by Django 6.0.6 on 2026-08-31 16:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_alter_show_checkout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='plan_advanced_annual',
            field=models.DecimalField(decimal_places=2, default=Decimal('499.90'), max_digits=10, verbose_name='Plano Avançado Anual'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='plan_advanced_monthly',
            field=models.DecimalField(decimal_places=2, default=Decimal('49.90'), max_digits=10, verbose_name='Plano Avançado Mensal'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='plan_basic_annual',
            field=models.DecimalField(decimal_places=2, default=Decimal('199.90'), max_digits=10, verbose_name='Plano Básico Anual'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='plan_basic_monthly',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.90'), max_digits=10, verbose_name='Plano Básico Mensal'),
        ),
    ]
