# Generated by Django 6.0.6 on 2026-09-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_systemsettings_plan_advanced_annual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproposal',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Contato'),
        ),
        migrations.AddField(
            model_name='commercialproposal',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local'),
        ),
    ]
