# Generated by Django 6.0.6 on 2026-09-02 02:34

from django.db import migrations, models


def backfill_show_lodging_data(apps, schema_editor):
    Show = apps.get_model('core', 'Show')
    RoomList = apps.get_model('core', 'RoomList')

    for show in Show.objects.all():
        # Obter a RoomList ativa ou mais recente deste show
        room_list = (
            RoomList.objects.filter(show=show)
            .order_by(
                models.Case(
                    models.When(status='PUBLICADA', then=1),
                    models.When(status='RASCUNHO', then=2),
                    models.When(status='ARQUIVADA', then=3),
                    default=4,
                    output_field=models.IntegerField()
                ),
                '-updated_at'
            )
            .first()
        )
        if room_list:
            updated_fields = []
            if not show.accommodation and room_list.hotel_name:
                show.accommodation = room_list.hotel_name
                updated_fields.append('accommodation')
            if not show.accommodation_city and room_list.city:
                show.accommodation_city = room_list.city
                updated_fields.append('accommodation_city')
            if not show.accommodation_address and room_list.address:
                show.accommodation_address = room_list.address
                updated_fields.append('accommodation_address')
            if not show.accommodation_link and getattr(room_list, 'accommodation_link', None):
                show.accommodation_link = room_list.accommodation_link
                updated_fields.append('accommodation_link')
            
            if updated_fields:
                show.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_commercialproposal_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='accommodation_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço da Hospedagem'),
        ),
        migrations.AddField(
            model_name='show',
            name='accommodation_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade da Hospedagem'),
        ),
        migrations.AlterField(
            model_name='show',
            name='accommodation',
            field=models.TextField(blank=True, null=True, verbose_name='Nome do Hotel'),
        ),
        migrations.AlterField(
            model_name='show',
            name='accommodation_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Localização'),
        ),
        migrations.RunPython(backfill_show_lodging_data, reverse_code=migrations.RunPython.noop),
    ]
