# Generated by Django 6.0.6 on 2026-09-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_show_accommodation_address_show_accommodation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='accommodation_responsible',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='show',
            name='accommodation_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato (Responsável)'),
        ),
    ]
