# Generated by Django 6.0.6 on 2026-09-04 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_show_accommodation_responsible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail do Destinatário')),
                ('responsible_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Responsável')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Hash SHA-256 do Token')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilizado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Token de Ativação',
                'verbose_name_plural': 'Tokens de Ativação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='ASAAS', max_length=30, verbose_name='Provedor')),
                ('gateway_event_id', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='ID do Evento no Gateway')),
                ('event_type', models.CharField(db_index=True, max_length=100, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(verbose_name='Payload Seguro do Evento')),
                ('processed', models.BooleanField(db_index=True, default=False, verbose_name='Processado?')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
            ],
            options={
                'verbose_name': 'Evento de Webhook',
                'verbose_name_plural': 'Eventos de Webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Referência Externa Única')),
                ('gateway_provider', models.CharField(default='ASAAS', max_length=30, verbose_name='Provedor de Gateway')),
                ('gateway_checkout_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID do Checkout no Gateway')),
                ('gateway_customer_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID do Cliente no Gateway')),
                ('gateway_subscription_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID da Assinatura no Gateway')),
                ('band_name', models.CharField(max_length=150, verbose_name='Nome da Banda / Artista')),
                ('responsible_name', models.CharField(max_length=200, verbose_name='Nome do Responsável')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=30, null=True, verbose_name='CPF ou CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail do Responsável')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone / WhatsApp')),
                ('plan_type', models.CharField(choices=[('BASICO', 'Básico'), ('AVANCADO', 'Avançado')], default='AVANCADO', max_length=20, verbose_name='Plano Escolhido')),
                ('billing_cycle', models.CharField(choices=[('MENSAL', 'Mensal'), ('ANUAL', 'Anual')], default='MENSAL', max_length=20, verbose_name='Ciclo de Cobrança')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Contratação')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago / Aprovado'), ('CANCELADO', 'Cancelado / Expirado'), ('FALHOU', 'Falhou')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status do Pedido')),
                ('provisioned_at', models.DateTimeField(blank=True, null=True, verbose_name='Data do Provisionamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pedido de Contratação',
                'verbose_name_plural': 'Pedidos de Contratação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bandsubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, verbose_name='Cancelar ao fim do período'),
        ),
        migrations.AddField(
            model_name='bandsubscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento'),
        ),
        migrations.AddField(
            model_name='bandsubscription',
            name='gateway_checkout_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True, verbose_name='ID do Checkout no Gateway'),
        ),
        migrations.AddField(
            model_name='bandsubscription',
            name='gateway_customer_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True, verbose_name='ID do Cliente no Gateway'),
        ),
        migrations.AddField(
            model_name='bandsubscription',
            name='gateway_external_reference',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True, verbose_name='Referência Externa do Gateway'),
        ),
        migrations.AddField(
            model_name='bandsubscription',
            name='gateway_provider',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Provedor do Gateway'),
        ),
        migrations.AddField(
            model_name='bandsubscription',
            name='gateway_subscription_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True, verbose_name='ID da Assinatura no Gateway'),
        ),
        migrations.AddField(
            model_name='bandsubscription',
            name='grace_period_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início da Tolerância'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='gateway_event_status',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Status do Evento no Gateway'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='gateway_external_reference',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True, verbose_name='Referência Externa no Gateway'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='gateway_invoice_url',
            field=models.URLField(blank=True, default=None, max_length=500, null=True, verbose_name='URL da Fatura no Gateway'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='gateway_payment_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True, verbose_name='ID do Pagamento no Gateway'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='gateway_provider',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Provedor do Gateway'),
        ),
        migrations.AddConstraint(
            model_name='bandsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_subscription_id__isnull', False), models.Q(('gateway_subscription_id', ''), _negated=True)), fields=('gateway_provider', 'gateway_subscription_id'), name='unique_subscription_per_gateway_provider'),
        ),
        migrations.AddConstraint(
            model_name='bandsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_checkout_id__isnull', False), models.Q(('gateway_checkout_id', ''), _negated=True)), fields=('gateway_provider', 'gateway_checkout_id'), name='unique_checkout_per_gateway_provider'),
        ),
        migrations.AddConstraint(
            model_name='billingrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_payment_id__isnull', False), models.Q(('gateway_payment_id', ''), _negated=True)), fields=('gateway_provider', 'gateway_payment_id'), name='unique_payment_per_gateway_provider'),
        ),
        migrations.AddField(
            model_name='bandactivationtoken',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_tokens', to='core.band', verbose_name='Banda'),
        ),
        migrations.AddField(
            model_name='signuporder',
            name='band',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_order', to='core.band', verbose_name='Banda Provisionada'),
        ),
        migrations.AddField(
            model_name='bandactivationtoken',
            name='signup_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_tokens', to='core.signuporder', verbose_name='Pedido de Origem'),
        ),
        migrations.AddConstraint(
            model_name='signuporder',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_checkout_id__isnull', False), models.Q(('gateway_checkout_id', ''), _negated=True)), fields=('gateway_provider', 'gateway_checkout_id'), name='unique_signup_order_checkout_per_gateway_provider'),
        ),
    ]
