# Generated by Django 6.0.6 on 2026-09-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_bandactivationtoken_paymentwebhookevent_signuporder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuporder',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago / Aprovado'), ('CANCELADO', 'Cancelado'), ('FALHOU', 'Falhou'), ('EXPIRADO', 'Expirado')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status do Pedido'),
        ),
    ]
