# Generated by Django 6.0.6 on 2026-09-04 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_alter_signuporder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuporder',
            name='activated_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_signup_order', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Inicial Ativado'),
        ),
    ]
