# Generated by Django 6.0.6 on 2026-09-04 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_signuporder_activated_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='installment_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número da Parcela (ex: 1 a 5)'),
        ),
        migrations.CreateModel(
            name='AnnualPlanPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('INITIAL', 'Compra Inicial'), ('RENEWAL', 'Renovação Anual')], default='INITIAL', max_length=20, verbose_name='Tipo da Compra')),
                ('gateway_provider', models.CharField(default='ASAAS', max_length=30, verbose_name='Provedor do Gateway')),
                ('gateway_external_reference', models.CharField(db_index=True, max_length=100, verbose_name='Referência Externa no Gateway')),
                ('gateway_installment_id', models.CharField(db_index=True, max_length=100, verbose_name='ID do Parcelamento (Installment) no Gateway')),
                ('installment_count', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Parcelas Escolhida')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Bruto Total (ex: 199.90)')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Líquido Recebido no Gateway')),
                ('coverage_start', models.DateField(verbose_name='Início da Vigência (12 meses)')),
                ('coverage_end', models.DateField(verbose_name='Fim da Vigência (12 meses)')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação Financeira')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Aprovada / Confirmada'), ('CANCELED', 'Cancelada')], db_index=True, default='CONFIRMED', max_length=20, verbose_name='Status da Compra Anual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('band_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_purchases', to='core.bandsubscription', verbose_name='Assinatura da Banda')),
                ('signup_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_purchases', to='core.signuporder', verbose_name='Pedido de Origem (se compra inicial)')),
            ],
            options={
                'verbose_name': 'Compra de Plano Anual',
                'verbose_name_plural': 'Compras de Planos Anuais',
                'ordering': ['-coverage_start', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='annual_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_records', to='core.annualplanpurchase', verbose_name='Compra Anual Vinculada'),
        ),
        migrations.CreateModel(
            name='GatewayPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_provider', models.CharField(default='ASAAS', max_length=30, verbose_name='Provedor do Gateway')),
                ('gateway_customer_id', models.CharField(db_index=True, max_length=100, verbose_name='ID do Cliente no Gateway')),
                ('encrypted_token', models.TextField(verbose_name='Token Criptografado (Fernet)')),
                ('card_brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bandeira do Cartão')),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos 4 Dígitos')),
                ('expiration_month', models.CharField(blank=True, max_length=2, null=True, verbose_name='Mês de Expiração')),
                ('expiration_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano de Expiração')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Método Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.bandsubscription', verbose_name='Assinatura Proprietária')),
            ],
            options={
                'verbose_name': 'Método de Pagamento Gateway',
                'verbose_name_plural': 'Métodos de Pagamento Gateway',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='annualplanpurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_installment_id__isnull', False), models.Q(('gateway_installment_id', ''), _negated=True)), fields=('gateway_provider', 'gateway_installment_id'), name='unique_installment_per_gateway_provider'),
        ),
        migrations.AddConstraint(
            model_name='gatewaypaymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('subscription', 'gateway_provider'), name='unique_active_payment_method_per_subscription_and_provider'),
        ),
    ]
