# Generated by Django 6.0.6 on 2026-09-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_billingrecord_installment_number_annualplanpurchase_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='annualplanpurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_external_reference__isnull', False), models.Q(('gateway_external_reference', ''), _negated=True)), fields=('gateway_provider', 'gateway_external_reference'), name='unique_annual_purchase_external_ref'),
        ),
    ]
