# Generated by Django 6.0.6 on 2026-09-04 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_annualplanpurchase_unique_annual_purchase_external_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualRenewalNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField(verbose_name='Data Prevista da Renovação')),
                ('plan_name', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('billing_cycle', models.CharField(default='ANUAL', max_length=20, verbose_name='Ciclo de Cobrança')),
                ('current_contracted_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Contratado Atual')),
                ('notified_renewal_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Notificado para Renovação')),
                ('installment_count', models.PositiveIntegerField(default=1, verbose_name='Parcelamento Previsto')),
                ('notice_type', models.CharField(choices=[('STANDARD', 'Aviso Padrão (Sem alteração)'), ('PRICE_CHANGE', 'Aviso de Atualização de Valor')], default='STANDARD', max_length=20, verbose_name='Tipo de Aviso')),
                ('email_recipient', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Destinatário')),
                ('scheduled_for', models.DateField(verbose_name='Agendado Para (D-30)')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio Efetivo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SENT', 'Enviado com Sucesso'), ('FAILED', 'Falha no Envio')], db_index=True, default='PENDING', max_length=20, verbose_name='Status do Aviso')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro (Sanitizada)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('band_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_notices', to='core.bandsubscription', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Aviso de Renovação Anual',
                'verbose_name_plural': 'Avisos de Renovação Anual',
                'ordering': ['-renewal_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('band_subscription', 'renewal_date'), name='unique_annual_renewal_notice_per_cycle')],
            },
        ),
    ]
