# Generated by Django 6.0.6 on 2026-09-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_annualrenewalnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualrenewalnotice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('SENT', 'Enviado com Sucesso'), ('FAILED', 'Falha no Envio'), ('SKIPPED', 'Ignorado / Não Entregue')], db_index=True, default='PENDING', max_length=20, verbose_name='Status do Aviso'),
        ),
    ]
