# Generated by Django 6.0.6 on 2026-09-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_alter_annualrenewalnotice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('SYSTEM_TEST', 'Teste de Sistema'), ('ACCOUNT_ACTIVATION', 'Ativação de Conta'), ('ANNUAL_RENEWAL_NOTICE', 'Aviso Pré-Renovação Anual'), ('ANNUAL_RENEWAL_SUCCESS', 'Renovação Anual Confirmada'), ('PAYMENT_OVERDUE', 'Aviso de Pagamento em Atraso'), ('SUBSCRIPTION_SUSPENDED', 'Assinatura Suspensa'), ('SUBSCRIPTION_CANCELLATION_SCHEDULED', 'Cancelamento Agendado'), ('CREDIT_CARD_CAPTURE_REFUSED', 'Recusa de Captura do Cartão')], db_index=True, max_length=50, verbose_name='Tipo de E-mail')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='E-mail do Destinatário')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto do E-mail')),
                ('template_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Template Base')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='Contexto Sanitizado (JSON)')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo do Objeto Relacionado')),
                ('related_object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Objeto Relacionado')),
                ('idempotency_key', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Chave de Idempotência')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Em Processamento'), ('RETRY', 'Aguardando Nova Tentativa'), ('SENT', 'Enviado com Sucesso'), ('FAILED', 'Falha Definitiva')], db_index=True, default='PENDING', max_length=20, verbose_name='Status da Entrega')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Tentativas')),
                ('max_attempts', models.PositiveIntegerField(default=6, verbose_name='Máximo de Tentativas')),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Próxima Tentativa Em')),
                ('sending_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Início do Processamento')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado Em')),
                ('last_error_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Último Código de Erro (Sanitizado)')),
                ('last_error_message', models.TextField(blank=True, null=True, verbose_name='Última Mensagem de Erro (Sanitizada)')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Message-ID SMTP Determinístico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
            ],
            options={
                'verbose_name': 'Entrega de E-mail',
                'verbose_name_plural': 'Entregas de E-mail',
                'ordering': ['-created_at'],
            },
        ),
    ]
