# Generated by Django 6.0.6 on 2026-09-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_emaildelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandactivationtoken',
            name='encrypted_token',
            field=models.TextField(blank=True, null=True, verbose_name='Token Criptografado (Fernet)'),
        ),
    ]
