# Generated by Django 6.0.6 on 2026-09-04 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_bandactivationtoken_encrypted_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(db_index=True, max_length=100, verbose_name='Nome do Job')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Iniciado Em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado Em')),
                ('status', models.CharField(choices=[('RUNNING', 'Em Execução'), ('SUCCESS', 'Sucesso'), ('PARTIAL', 'Parcialmente Concluído'), ('FAILED', 'Falha'), ('SKIPPED_LOCKED', 'Ignorado (Lock Ativo)')], db_index=True, default='RUNNING', max_length=20, verbose_name='Status da Execução')),
                ('processed_count', models.PositiveIntegerField(default=0, verbose_name='Registros Processados')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Sucessos')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Ignorados')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Falhas')),
                ('error_summary', models.TextField(blank=True, null=True, verbose_name='Resumo de Erros (Sanitizado)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
            ],
            options={
                'verbose_name': 'Execução de Job Agendado',
                'verbose_name_plural': 'Execuções de Jobs Agendados',
                'ordering': ['-started_at'],
            },
        ),
    ]
