# Generated by Django 6.0.6 on 2026-09-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_scheduledjobrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandsubscription',
            name='commercial_condition',
            field=models.CharField(choices=[('PAGO', 'Pago'), ('PARCERIA', 'Parceria')], db_index=True, default='PAGO', max_length=20, verbose_name='Condição Comercial'),
        ),
    ]
