# Generated by Django 6.0.6 on 2026-09-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_bandsubscription_commercial_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuporder',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço / Logradouro'),
        ),
        migrations.AddField(
            model_name='signuporder',
            name='address_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='signuporder',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='signuporder',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='signuporder',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='signuporder',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='signuporder',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado / UF'),
        ),
    ]
