# Generated by Django 6.0.6 on 2026-09-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_user_phone_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Exige troca de senha no próximo acesso'),
        ),
    ]
