# Generated by Django 6.0.6 on 2026-09-16 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_show_created_at_show_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuporder',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_orders', to='core.band', verbose_name='Banda Provisionada'),
        ),
    ]
