# Generated by Django 6.0.6 on 2026-09-16 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    User = apps.get_model('core', 'User')
    UserBandMembership = apps.get_model('core', 'UserBandMembership')

    for user in User.objects.filter(band__isnull=False):
        # Idempotência: não duplica se já existir
        UserBandMembership.objects.get_or_create(
            user=user,
            band=user.band,
            defaults={
                'role': user.role or 'INTEGRANTE',
                'is_active': user.is_active
            }
        )


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_alter_signuporder_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBandMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRODUTOR', 'Produtor'), ('EMPRESARIO', 'Empresário'), ('INTEGRANTE', 'Integrante')], default='INTEGRANTE', max_length=20, verbose_name='Perfil nesta Banda')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vínculo Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='core.band', verbose_name='Banda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Vínculo Usuário-Banda',
                'verbose_name_plural': 'Vínculos Usuário-Banda',
                'constraints': [models.UniqueConstraint(fields=('user', 'band'), name='unique_user_band_membership')],
            },
        ),
        migrations.RunPython(forwards_func, backwards_func),
    ]
