# Generated by Django 6.0.6 on 2026-09-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_user_band_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='arrival_airport',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aeroporto de Desembarque'),
        ),
        migrations.AddField(
            model_name='show',
            name='arrival_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local de Chegada'),
        ),
        migrations.AddField(
            model_name='show',
            name='arrival_location_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Local de Chegada'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_airline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa Aérea (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_arrival_airport',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aeroporto de Desembarque (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_arrival_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local de Chegada (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_arrival_location_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Local de Chegada (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Previsão Chegada (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_boarding_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Horário de Embarque (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_departure_airport',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aeroporto de Embarque (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_departure_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local de Saída (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_departure_location_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Local de Saída (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_departure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Horário Saída (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_distance_km',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distância (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_flight_arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Previsão de Chegada do Voo (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_flight_departure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Horário do Voo (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_flight_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Voo (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_has_air_travel',
            field=models.BooleanField(default=False, verbose_name='Inclui trecho aéreo (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_transport',
            field=models.TextField(blank=True, null=True, verbose_name='Meio de Transporte (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_transport_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato do Transporte (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_transport_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações do Deslocamento (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='artist_travel_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempo de Deslocamento (Artista)'),
        ),
        migrations.AddField(
            model_name='show',
            name='boarding_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Horário de Embarque'),
        ),
        migrations.AddField(
            model_name='show',
            name='departure_airport',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aeroporto de Embarque'),
        ),
        migrations.AddField(
            model_name='show',
            name='flight_arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Previsão de Chegada do Voo'),
        ),
        migrations.AddField(
            model_name='show',
            name='flight_departure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Horário do Voo'),
        ),
        migrations.AddField(
            model_name='show',
            name='has_air_travel',
            field=models.BooleanField(default=False, verbose_name='Inclui trecho aéreo'),
        ),
        migrations.AddField(
            model_name='show',
            name='has_specific_artist_logistics',
            field=models.BooleanField(default=False, verbose_name='Logística Específica para Artista'),
        ),
        migrations.AddField(
            model_name='show',
            name='has_specific_tech_logistics',
            field=models.BooleanField(default=False, verbose_name='Logística Específica para Técnica'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_airline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa Aérea (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_arrival_airport',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aeroporto de Desembarque (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_arrival_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local de Chegada (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_arrival_location_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Local de Chegada (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Previsão Chegada (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_boarding_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Horário de Embarque (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_departure_airport',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aeroporto de Embarque (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_departure_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local de Saída (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_departure_location_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Local de Saída (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_departure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Horário Saída (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_distance_km',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distância (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_flight_arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Previsão de Chegada do Voo (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_flight_departure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Horário do Voo (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_flight_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Voo (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_has_air_travel',
            field=models.BooleanField(default=False, verbose_name='Inclui trecho aéreo (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_transport',
            field=models.TextField(blank=True, null=True, verbose_name='Meio de Transporte (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_transport_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato do Transporte (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_transport_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações do Deslocamento (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='tech_travel_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempo de Deslocamento (Técnica)'),
        ),
        migrations.AddField(
            model_name='show',
            name='transport_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações do Deslocamento'),
        ),
        migrations.AlterField(
            model_name='show',
            name='airline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa Aérea'),
        ),
        migrations.AlterField(
            model_name='show',
            name='boarding_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Embarque (Legado)'),
        ),
        migrations.AlterField(
            model_name='show',
            name='flight_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Voo'),
        ),
        migrations.AlterField(
            model_name='show',
            name='transport',
            field=models.TextField(blank=True, null=True, verbose_name='Meio de Transporte'),
        ),
        migrations.AlterField(
            model_name='show',
            name='transport_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato do Transporte'),
        ),
    ]
