# Generated by Django 6.0.6 on 2026-09-18 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_show_arrival_airport_show_arrival_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID do Evento no Google Calendar'),
        ),
        migrations.CreateModel(
            name='GoogleCalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_account_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Conta Google Conectada')),
                ('calendar_id', models.CharField(default='primary', max_length=255, verbose_name='ID do Calendário Google')),
                ('calendar_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Calendário Selecionado')),
                ('encrypted_access_token', models.TextField(blank=True, null=True, verbose_name='Access Token Criptografado')),
                ('encrypted_refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token Criptografado')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiração do Access Token')),
                ('status', models.CharField(choices=[('CONNECTED', 'Conectado'), ('ERROR', 'Erro / Expirado'), ('DISCONNECTED', 'Desconectado')], db_index=True, default='DISCONNECTED', max_length=20, verbose_name='Status da Integração')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('last_error_message', models.TextField(blank=True, null=True, verbose_name='Última Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Conexão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('band', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_integration', to='core.band', verbose_name='Banda')),
            ],
            options={
                'verbose_name': 'Integração Google Calendar',
                'verbose_name_plural': 'Integrações Google Calendar',
            },
        ),
    ]
