# Generated by Django 6.0.6 on 2026-09-21 15:17

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_show_google_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandactivationtoken',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Alvo (Conta Existente)'),
        ),
        migrations.AddField(
            model_name='bandactivationtoken',
            name='token_type',
            field=models.CharField(choices=[('NEW_ACCOUNT', 'Criação de Nova Conta'), ('LINK_BAND', 'Vincular à Conta Existente')], db_index=True, default='NEW_ACCOUNT', max_length=20, verbose_name='Tipo de Token'),
        ),
        migrations.AddField(
            model_name='signuporder',
            name='responsible_cpf',
            field=models.CharField(blank=True, db_index=True, help_text='CPF da pessoa física titular do acesso.', max_length=11, null=True, validators=[core.models.validate_cpf_digits], verbose_name='CPF do Responsável'),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, help_text='11 dígitos numéricos do CPF do titular da conta.', max_length=11, null=True, unique=True, validators=[core.models.validate_cpf_digits], verbose_name='CPF do Responsável'),
        ),
        migrations.AlterField(
            model_name='emaildelivery',
            name='email_type',
            field=models.CharField(choices=[('SYSTEM_TEST', 'Teste de Sistema'), ('ACCOUNT_ACTIVATION', 'Ativação de Conta'), ('BAND_ADDED_TO_EXISTING_ACCOUNT', 'Nova Banda para Conta Existente'), ('ANNUAL_RENEWAL_NOTICE', 'Aviso Pré-Renovação Anual'), ('ANNUAL_RENEWAL_SUCCESS', 'Renovação Anual Confirmada'), ('PAYMENT_OVERDUE', 'Aviso de Pagamento em Atraso'), ('SUBSCRIPTION_SUSPENDED', 'Assinatura Suspensa'), ('SUBSCRIPTION_CANCELLATION_SCHEDULED', 'Cancelamento Agendado'), ('CREDIT_CARD_CAPTURE_REFUSED', 'Recusa de Captura do Cartão')], db_index=True, max_length=50, verbose_name='Tipo de E-mail'),
        ),
        migrations.AlterField(
            model_name='signuporder',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CPF ou CNPJ para Cobrança'),
        ),
    ]
