# Generated by Django 6.0.6 on 2026-09-23 03:53

import core.file_policy
import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_bandactivationtoken_target_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandGeneralExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
                ('date', models.DateField(verbose_name='Data')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.general_expense_upload_path, validators=[core.file_policy.validate_file_size_and_type], verbose_name='Comprovante / Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_expenses', to='core.band', verbose_name='Banda')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_general_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Despesa Geral da Banda',
                'verbose_name_plural': 'Despesas Gerais da Banda',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
