# Generated by Django 6.0.6 on 2026-09-24 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_set_empresarios_danniel_vieira'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Líquido Recebido'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='net_amount_manual',
            field=models.BooleanField(default=False, verbose_name='Líquido Ajustado Manualmente?'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='net_amount_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Correção do Líquido'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='net_amount_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Correção'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='net_amount_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_billings', to=settings.AUTH_USER_MODEL, verbose_name='Corrigido por'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
    ]
