"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
import os
import urllib.parse
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# ==============================================================================
# ENVIRONMENT DETECTION & LOAD_DOTENV
# ==============================================================================

RUNNING_ON_RAILWAY = bool(os.getenv("RAILWAY_ENVIRONMENT_ID"))
PRE_DJANGO_ENV = os.getenv("DJANGO_ENV", "").strip().lower()
PRE_IS_SECURE_ENV = PRE_DJANGO_ENV in {"staging", "production"}

if not RUNNING_ON_RAILWAY and not PRE_IS_SECURE_ENV:
    from dotenv import load_dotenv
    load_dotenv()

_raw_env = os.getenv("DJANGO_ENV", "development").strip().lower()
if _raw_env not in {"development", "test", "staging", "production"}:
    raise ImproperlyConfigured("DJANGO_ENV inválido.")
DJANGO_ENV = _raw_env

IS_PRODUCTION = RUNNING_ON_RAILWAY or (DJANGO_ENV in {"staging", "production"})

# ==============================================================================
# ENVIRONMENT PARSERS
# ==============================================================================

def env_bool(name, default):
    val = os.getenv(name)
    if val is None:
        return default
    val_lower = val.strip().lower()
    if val_lower in ('1', 'true', 'yes', 'on'):
        return True
    elif val_lower in ('0', 'false', 'no', 'off'):
        return False
    else:
        raise ImproperlyConfigured(f"Invalid boolean value for environment variable {name}")

def env_list(name, default_list):
    val = os.getenv(name)
    if val is None:
        return default_list
    items = [item.strip() for item in val.split(',') if item.strip()]
    return items

def env_int(name, default):
    val = os.getenv(name)
    if val is None:
        return default
    try:
        parsed = int(val.strip())
        if parsed < 0:
            raise ValueError
        return parsed
    except ValueError:
        raise ImproperlyConfigured(f"Invalid positive integer value for environment variable {name}")

# ==============================================================================
# CORE SETTINGS
# ==============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# DEBUG
DEBUG = env_bool("DEBUG", default=not IS_PRODUCTION)
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured("DEBUG=True não é permitido em ambiente seguro.")

# SECRET_KEY
LOCAL_FALLBACK_KEY = 'chave-local-insegura-para-desenvolvimento'
SECRET_KEY = os.getenv('SECRET_KEY', LOCAL_FALLBACK_KEY)

if IS_PRODUCTION:
    if not SECRET_KEY or SECRET_KEY == LOCAL_FALLBACK_KEY:
        raise ImproperlyConfigured("A secure SECRET_KEY must be provided in production.")
    if len(SECRET_KEY) < 50 or SECRET_KEY.startswith('django-insecure-') or len(set(SECRET_KEY)) < 5:
        raise ImproperlyConfigured("SECRET_KEY does not meet production security requirements.")

# ALLOWED_HOSTS
default_hosts = ['localhost', '127.0.0.1', '[::1]', 'testserver'] if not IS_PRODUCTION else []
ALLOWED_HOSTS_RAW = env_list('ALLOWED_HOSTS', default_hosts)

railway_domain = os.getenv("RAILWAY_PUBLIC_DOMAIN", "").strip()
if railway_domain:
    ALLOWED_HOSTS_RAW.insert(0, railway_domain)

if IS_PRODUCTION:
    if not ALLOWED_HOSTS_RAW:
        raise ImproperlyConfigured("ALLOWED_HOSTS is required in production.")
    if '*' in ALLOWED_HOSTS_RAW:
        raise ImproperlyConfigured("Wildcard '*' in ALLOWED_HOSTS is forbidden in production.")

ALLOWED_HOSTS = []
for host in ALLOWED_HOSTS_RAW:
    host_clean = host.strip().lower()
    if not host_clean:
        if IS_PRODUCTION:
            raise ImproperlyConfigured("Empty ALLOWED_HOSTS entry is not allowed.")
        continue

    if IS_PRODUCTION:
        if '://' in host_clean or '/' in host_clean or '?' in host_clean or '#' in host_clean or '@' in host_clean:
            raise ImproperlyConfigured(f"Invalid characters in ALLOWED_HOSTS entry: {host_clean}")

    if host_clean not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host_clean)

if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured("ALLOWED_HOSTS cannot be empty in production.")

# CSRF_TRUSTED_ORIGINS
default_csrf = ['http://localhost:8000'] if not IS_PRODUCTION else []
CSRF_TRUSTED_ORIGINS_RAW = env_list('CSRF_TRUSTED_ORIGINS', default_csrf)

if railway_domain:
    # A railway_domain ja passou por strip()
    CSRF_TRUSTED_ORIGINS_RAW.insert(0, f"https://{railway_domain.lower()}")

CSRF_TRUSTED_ORIGINS = []
for origin in CSRF_TRUSTED_ORIGINS_RAW:
    origin_clean = origin.strip().lower()
    if not origin_clean:
        continue

    if IS_PRODUCTION:
        if '*' in origin_clean:
            raise ImproperlyConfigured("Wildcard '*' in CSRF_TRUSTED_ORIGINS is forbidden in production.")

        parsed = urllib.parse.urlparse(origin_clean)
        if parsed.scheme != 'https':
            raise ImproperlyConfigured(f"CSRF_TRUSTED_ORIGINS must use https in production. Found: {origin_clean}")
        if not parsed.hostname:
             raise ImproperlyConfigured("CSRF_TRUSTED_ORIGINS missing hostname.")
        if parsed.username or parsed.password or (parsed.path and parsed.path != '/') or parsed.query or parsed.fragment:
            raise ImproperlyConfigured(f"CSRF_TRUSTED_ORIGINS format is invalid. Cannot contain credentials, paths, queries or fragments: {origin_clean}")

    if origin_clean not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin_clean)

if IS_PRODUCTION and not CSRF_TRUSTED_ORIGINS:
    raise ImproperlyConfigured("CSRF_TRUSTED_ORIGINS cannot be empty in production.")

# Web Push Keys
VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY', '').strip()
VAPID_PRIVATE_KEY = os.environ.get('VAPID_PRIVATE_KEY', '').strip()
VAPID_SUBJECT = os.environ.get('VAPID_SUBJECT', '').strip()

# Custom CSRF Failure View
CSRF_FAILURE_VIEW = 'core.push_views.custom_csrf_failure'

# ==============================================================================
# DATABASE
# ==============================================================================

db_url = os.getenv('DATABASE_URL')

if IS_PRODUCTION and not db_url:
    raise ImproperlyConfigured("DATABASE_URL is required in production. No silent SQLite fallback allowed.")

if db_url:
    if IS_PRODUCTION and not db_url.startswith('postgres://') and not db_url.startswith('postgresql://'):
         raise ImproperlyConfigured("Only PostgreSQL is supported in production.")
    DATABASES = {
        'default': dj_database_url.config(
            default=db_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ==============================================================================
# SECURITY, HTTPS & PROXY
# ==============================================================================

# Reconhecer HTTPS através de Load Balancers no Railway
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Redirecionamento SSL
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=IS_PRODUCTION)
if IS_PRODUCTION and not SECURE_SSL_REDIRECT:
    raise ImproperlyConfigured("SECURE_SSL_REDIRECT deve estar ativo em produção.")

# Cookies Seguros
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION

# HSTS
SECURE_HSTS_SECONDS = env_int('SECURE_HSTS_SECONDS', default=3600 if IS_PRODUCTION else 0)
if IS_PRODUCTION and SECURE_HSTS_SECONDS <= 0:
    raise ImproperlyConfigured("SECURE_HSTS_SECONDS deve ser maior que zero em produção.")

SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', default=False)
if IS_PRODUCTION and SECURE_HSTS_PRELOAD and (not SECURE_HSTS_INCLUDE_SUBDOMAINS or SECURE_HSTS_SECONDS <= 0):
    raise ImproperlyConfigured("Preload HSTS is invalid without subdomains and seconds > 0.")

# ==============================================================================
# APPLICATION DEFINITION
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.web_push_admin',
                'core.context_processors.system_settings_processor',
            ],
        },

    },
]

WSGI_APPLICATION = 'config.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# ==============================================================================
# STATIC & MEDIA FILES
# ==============================================================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'core' / 'static']

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

# ==============================================================================
# LOGGING
# ==============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('LOG_LEVEL', 'INFO'),
    },
}

AUTH_USER_MODEL = 'core.User'

# ==============================================================================
# WEB PUSH ALERT SETTINGS
# ==============================================================================

WEB_PUSH_ALERT_EMAIL_ENABLED = env_bool('WEB_PUSH_ALERT_EMAIL_ENABLED', default=False)
WEB_PUSH_ALERT_EMAIL_RECIPIENTS = os.getenv('WEB_PUSH_ALERT_EMAIL_RECIPIENTS', '')
WEB_PUSH_ALERT_EMAIL_FROM = os.getenv('WEB_PUSH_ALERT_EMAIL_FROM', 'webmaster@localhost')
WEB_PUSH_ALERT_DASHBOARD_URL = os.getenv('WEB_PUSH_ALERT_DASHBOARD_URL', 'http://localhost:8000/painel/web-push/')
WEB_PUSH_ALERT_EMAIL_MIN_SEVERITY = os.getenv('WEB_PUSH_ALERT_EMAIL_MIN_SEVERITY', 'WARNING')
WEB_PUSH_ALERT_EMAIL_MAX_ATTEMPTS = env_int('WEB_PUSH_ALERT_EMAIL_MAX_ATTEMPTS', default=3)
WEB_PUSH_ALERT_EMAIL_RETRY_MINUTES = env_int('WEB_PUSH_ALERT_EMAIL_RETRY_MINUTES', default=15)
WEB_PUSH_ALERT_CYCLE_LOCK_MINUTES = env_int('WEB_PUSH_ALERT_CYCLE_LOCK_MINUTES', default=10)

# ==============================================================================
# ASAAS INTEGRATION SETTINGS
# ==============================================================================

ASAAS_ENVIRONMENT = os.getenv('ASAAS_ENVIRONMENT', 'sandbox').strip().lower()
ASAAS_BASE_URL = os.getenv('ASAAS_BASE_URL', 'https://api-sandbox.asaas.com/v3' if ASAAS_ENVIRONMENT == 'sandbox' else 'https://api.asaas.com/v3')
ASAAS_API_KEY = os.getenv('ASAAS_API_KEY', None)
ASAAS_WEBHOOK_TOKEN = os.getenv('ASAAS_WEBHOOK_TOKEN', None)
PAYMENT_TOKEN_ENCRYPTION_KEY = os.getenv('PAYMENT_TOKEN_ENCRYPTION_KEY', None)
ACTIVATION_TOKEN_ENCRYPTION_KEY = os.getenv('ACTIVATION_TOKEN_ENCRYPTION_KEY', None)
PAYMENTS_LIVE_ENABLED = env_bool('PAYMENTS_LIVE_ENABLED', default=(ASAAS_ENVIRONMENT == 'sandbox'))


# ==============================================================================
# EMAIL SETTINGS
# ==============================================================================
EMAIL_PROVIDER = os.getenv('EMAIL_PROVIDER', 'smtp').strip().lower()

# 1. Resend HTTPS Provider Settings
RESEND_API_KEY = os.getenv('RESEND_API_KEY', None)
RESEND_FROM_EMAIL = os.getenv('RESEND_FROM_EMAIL', None)
RESEND_REPLY_TO_EMAIL = os.getenv('RESEND_REPLY_TO_EMAIL', None)

# 2. Django SMTP Settings (Legado / Fallback)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend').strip()
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com').strip()
EMAIL_PORT = env_int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', default=False)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'backstagepro.site@gmail.com').strip()
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', None)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Backstage Pro <backstagepro.site@gmail.com>').strip()
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL).strip()
EMAIL_TIMEOUT = env_int('EMAIL_TIMEOUT', default=10)

# FAIL-CLOSED VALIDATION: Se o provider for SMTP e o backend for explicitamente SMTP,
# exige que EMAIL_HOST_USER e EMAIL_HOST_PASSWORD estejam definidos.
if EMAIL_PROVIDER == 'smtp' and 'smtp.EmailBackend' in EMAIL_BACKEND:
    if not EMAIL_HOST_USER:
        raise ImproperlyConfigured("EMAIL_HOST_USER must be configured when using SMTP EmailBackend.")
    if not EMAIL_HOST_PASSWORD:
        raise ImproperlyConfigured("EMAIL_HOST_PASSWORD must be configured when using SMTP EmailBackend.")


